### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by krivadna** [guelfoweb/knock#153]
~/knock $ python knockpy.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/knock/knockpy.py", line 7, in <module>
    from knockpy import knockpy
  File "/data/data/com.termux/files/home/knock/knockpy.py", line 7, in <module>
    from knockpy import knockpy
ImportError: cannot import name 'knockpy' from partially initialized module 'knockpy' (most likely due to a circular import) (/data/data/com.termux/files/home/knock/knockpy.py)

**Comment by drego85** [comment]
Hi, 
The error you're encountering occurs because you're trying to run `knockpy` directly from the `.py` file, which leads to a circular import issue. Instead of executing `knockpy.py` directly, you need to install Knockpy properly using `pip`. Here are the steps to follow:

1. First, make sure you have `pip` installed.
2. Then, install Knockpy by running the following command:

```bash
pip install git+https://github.com/guelfoweb/knock.git
```

Once the installation is complete, you should be able to run Knockpy without any issues by using the command:

```bash
knockpy <target_domain>
```
