### ISSUE TITLE
ImportError: No module named python-dnspython

### ISSUE THREAD

**Issue by Anirbansikder** [guelfoweb/knock#87]
Whenever I run this file I get :
```
ImportError: No module named python-dnspython
pip install dnspython
```
and I already have dnspython module.

How to handle this ?

**Comment by rayearlK** [comment]
Hello Anirbansikder,
I think it might be the python (pip) configuration problem in your system. 
Try explicit install: something like this: **# python -m pip install dnspython**

**Comment by benchacham** [comment]
Somebody fixed this issue? I m facing the same issue ...
Pls advise

**Comment by C3SB1C** [comment]
Knock requires a Python 2.7.6 version, so, Probably the problem is dnspython. Because Python 2.x support ended with the release of 1.16.0. The dnspython 2.0.0 and later, only support Python 3.6 and later.
Is possible that you will need a virtual environment to use python 2.7.6 (required by knock), take a look to:
www.kali.org/docs/general-use/using-eol-python-versions/

If you don't have troubles with the python version, then try modifiying the dnspython version. I downloaded the 1.16 version of dnspython from:
https://github.com/rthalley/dnspython/releases/tag/v1.16.0
(Remember that this version doesn't have support anymore)
when you're installing the setup.py  from the knock folder, make sure that you have the proper dnspython version (1.16) on the path:

![knock01](https://user-images.githubusercontent.com/78324142/106399271-4024ae00-63dd-11eb-85bb-8d41d19d81a8.jpg)

I had the same problem, and this is what works for me. I Hope it helps, regards.

**Comment by drego85** [comment]
dnspython has been removed from the new Knock version.

**Comment by vascoarizna** [comment]
You should use `import dns`
